### ISSUE TITLE
[ADD] Arweave Name Service - ANS

### ISSUE THREAD

**Issue by charmful0x** [nicolasverlhiac/arweave-list#1]
## Name
Arweave Name Service (ANS)

## Description

Arweave Names Service combines a decentralized domains naming service and a decentralized Gravatar-like protocol into a new protocol called ANS.

## Decentralized alternative to :

* [Gravatar](https://en.gravatar.com/)

## Infos

* `Project URL`: https://ar.page
* `Github URL`: https://github.com/decentldotland/ANS
* `Image URL`: you could use the same image (logo) used for [DecentLand](https://decent.land)

**Comment by nicolasverlhiac** [comment]
Thanks @charmful0x !

The list has been updated:
<img width="795" alt="Capture d’écran 2022-07-19 à 14 29 57" src="https://user-images.githubusercontent.com/5034521/179750472-bdcc1e2a-e915-49e6-9f1b-252a3232e506.png">

**Comment by charmful0x** [comment]
Thank you!
