### ISSUE TITLE
📨 [NEW]: Keystone Wallet

### ISSUE THREAD

**Issue by angrymouse** [nicolasverlhiac/arweave-list#10]
### What is the project’s name ?

Keystone Wallet

### Please provide a short description of this project.

Keystone is first hardware wallet with arweave support.

### This project is a decentralized alternative to which service/app?

Not centralized, but Ledger, Trezor, SafePal. Also to hot wallets.

### In which category does this project fit (one or more)?

Wallet

### What are the tags that best describe this project?

non-custodial-wallet, beta, open-source

### Project logo

<img width="137" alt="keystone" src="https://user-images.githubusercontent.com/40735471/221050013-6cfab08c-f20c-4542-a4fa-688bde3f9731.png">

### Link to the projet

https://keyst.one

### Twitter @name

@KeystoneWallet

### Discord invitation link

https://discord.gg/2dVa3HvGN8

### Are you related to this project?

- [ ] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @angrymouse !

Thanks for your contribution ( one more time !). For the "decentralized alternative to" part, as you say, the projects are also decentralized alternatives, but maybe we can put exchanges instead?  What do you think about it?

<img width="787" alt="Capture d’écran 2023-02-24 à 11 09 53" src="https://user-images.githubusercontent.com/5034521/221151976-253746ab-b820-4618-9b13-1cbd99f6ddd2.png">

**Comment by angrymouse** [comment]
@nicolasverlhiac Yeah might be good idea, but usually alternatives to centralized exchanges are decentralized exhcnages... Not wallets

**Comment by nicolasverlhiac** [comment]
@angrymouse You're right ! Regarding Keystone Wallet, the decentralized alternatives seem a bit blurry.
The discussion remains open :)

**Comment by angrymouse** [comment]
@nicolasverlhiac I think custodial wallets like paypal's or webmoney's crypto wallets can be considered as centralized alternatives 🤔
