### ISSUE TITLE
📨 [NEW]: Streamr

### ISSUE THREAD

**Issue by fonty1** [nicolasverlhiac/arweave-list#11]
### What is the project’s name ?

Streamr

### Please provide a short description of this project.

Streamr is a peer-to-peer pub/sub network for streaming data and real-time messaging. 

Web3 projects typically see Streamr as middleware. Streamr is used inside oracles, IoT pipelines, messaging apps, and all sorts of event-driven applications. 

Streamr is used as the data delivery network for the RedStone oracle and for the LogStore time series database. These applications use Streamr to deliver the data to and from Arweave for permanent storage with end-to-end decentralization.

### This project is a decentralized alternative to which service/app?

Google Pub/Sub, PubNub

### In which category does this project fit (one or more)?

Infrastructure

### What are the tags that best describe this project?

open-source, protocol

### Project logo

![Vertical colour lockup](https://github.com/nicolasverlhiac/arweave-list/assets/1593398/5b704067-625c-4193-a035-120f73c7364c)

### Link to the projet

https://streamr.network

### Twitter @name

@streamr

### Discord invitation link

https://discord.gg/gZAm8P7hK8

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @fonty1 , thank you very much for your contribution.

The Streamr project has been added to the list !
[https://list.weavescan.com/project/streamr](https://list.weavescan.com/project/streamr)

<img width="792" alt="Capture d’écran 2023-05-29 à 00 09 49" src="https://github.com/nicolasverlhiac/arweave-list/assets/5034521/277c9bfc-8f6c-406f-8ad4-a6b4376ef60f">
