### ISSUE TITLE
Chore(wallet): Avana wallet sunset

### ISSUE THREAD

**Issue by atticusofsparta** [nicolasverlhiac/arweave-list#12]
Avana wallet is sunsetting in september of 2023, should probably be removed from the lists

![image](https://github.com/nicolasverlhiac/arweave-list/assets/85306700/0bd493fe-b6c0-4a3f-9ac0-1151ed93d2f6)

**Comment by nicolasverlhiac** [comment]
Hi @atticusofsparta , thank you very much for this update, the project has just been removed from the list. 
https://list.weavescan.com/changelog
