### ISSUE TITLE
📨 [NEW]: Smartweaver - Dynamically generated Smartweave Contract interface

### ISSUE THREAD

**Issue by atticusofsparta** [nicolasverlhiac/arweave-list#13]
### What is the project’s name ?

Smartweaver

### Please provide a short description of this project.

Smartweaver is a permaweb dapp that uses babeljs to traverse smartweave contract code, pull the exposed functions and their required props, to provide users with a GUI interface for smartweave contracts. It could be considered as renderer as well with a bit of tweaking.

This enables a basic interface to contracts allow access to all functions on them.

### This project is a decentralized alternative to which service/app?

This project is fairly unique, but was inspired by the etherscan contract interface.

### In which category does this project fit (one or more)?

NFT, DAO Tooling, Developer Tooling, News & Knowledge, Infrastructure, Wallet

### What are the tags that best describe this project?

free, web-app, open-source, DAO, smart-contract, dapp

### Project logo

Project Logo

### Link to the projet

https://github.com/atticusofsparta/smartweave-inspector

### Permaweb link to the projet

https://smartweaver.arweave.dev

### Twitter @name

@SanOfABee

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @atticusofsparta, thank you very much for your contribution.

The Smartweaver project has been added to the list !
https://list.weavescan.com/project/smartweaver

<img width="798" alt="Capture d’écran 2023-11-10 à 15 00 29" src="https://github.com/nicolasverlhiac/arweave-list/assets/5034521/d5b52fc4-d186-4f0e-a732-10dcb28705bb">
