### ISSUE TITLE
📨 [NEW]: request to submit a list at https://list.weavescan.com/list/nft

### ISSUE THREAD

**Issue by captvicky** [nicolasverlhiac/arweave-list#14]
### What is the project’s name ?

Remembering Satoshi

### Please provide a short description of this project.

it was created to remind us of Satoshi Nakamoto who has contributed to the decentralized financial industry and gives hope for the importance of more transparent economic progress by using Bitcoin as peer to peer electronic cash.
This NFT was made from just 8 images that tell the story of Satoshi's journey in fighting for his vision and mission for Bitcoin. Each image contains 21 copies which reflects the number of 21 million bitcoins that can only be mined.

### This project is a decentralized alternative to which service/app?

None

### In which category does this project fit (one or more)?

NFT

### What are the tags that best describe this project?

nft

### Project logo

![little avatar](https://github.com/nicolasverlhiac/arweave-list/assets/28209294/6260b225-bef2-4ab2-83fa-57e494148142)

### Link to the projet

https://satoshijourney_origae6.ar-io.dev/

### Permaweb link to the projet

https://7csxnvhrqynun3za2gyovez3likz7wuvjso27tbkh3lhatb2jira.arweave.net/-KV21PGGG0bvINGw6pM7WhWf2pVMna_MKj7WcEw6SiI/

### Twitter @name

@capt_vicky

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @captvicky, thank you for submitting your project.

For the time being, projects involving NFTs are only accepted if they are a platform/tool at the service of NFTs.
This submission remains open for the day when we have room for NFT projects stricto senso.

**Comment by captvicky** [comment]
No problem, thank you for letting me know!

Pada Sen, 26 Feb 2024 pukul 17.46 Nicolas Verlhiac ***@***.***>
menulis:
