### ISSUE TITLE
📨 [NEW]: Akord update

### ISSUE THREAD

**Issue by pascaljb** [nicolasverlhiac/arweave-list#15]
### What is the project’s name ?

Akord

### Please provide a short description of this project.

Akord offers digital vaults on Arweave though a web app, as well as an API and CLI for developers to build on AkordJS which is open source. You can store files privately and publicly, as well as mint Atomic NFTs.

### This project is a decentralized alternative to which service/app?

Dropbox

### In which category does this project fit (one or more)?

NFT, Developer Tooling, Storage

### Project logo

![AK new fav](https://github.com/nicolasverlhiac/arweave-list/assets/57722629/122dc1b0-f703-4f1c-95cf-818916f51178)

### Link to the projet

https://akord.com/

### Twitter @name

@AkordTeam

### Discord invitation link

https://discord.com/invite/DVkyUtcKGn

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @pascaljb , thank you for the update : https://list.weavescan.com/project/akord

**Comment by pascaljb** [comment]
Hey @nicolasverlhiac, thanks for that, but my intention was to get us listed on developer tooling and NFT, as well as storage. It seems while we're now on the NFT section, we don't now appear in storage and also not in dev tooling.

**Comment by pascaljb** [comment]
@nicolasverlhiac any chance we can address the above issues? thanks!

**Comment by nicolasverlhiac** [comment]
Hi @pascaljb, there's a development in progress to handle this case, maybe next week. The initial goal was to avoid displaying the same project in too many categories.

**Comment by pascaljb** [comment]
Hey @nicolasverlhiac, OK I understand. I think for us then it would make most sense to list 'Akord' under Storage and 'AkordJS' under developer tooling, as that's our open source library for file management on Arweave using our digital vault system. We're less fussed about the NFT category at this point if you want to limit the number of categories. Thanks

**Comment by nicolasverlhiac** [comment]
Hi @pascaljb , I've made the changes to multi-category management : 

### List item
![CleanShot 2024-03-25 at 13 03 11@2x](https://github.com/nicolasverlhiac/arweave-list/assets/5034521/7a74281c-6a54-4e5b-8e6a-f64998cc9e10)

### Project page : 
![CleanShot 2024-03-25 at 13 03 18@2x](https://github.com/nicolasverlhiac/arweave-list/assets/5034521/bbbd49c3-960d-41c6-9327-9329cd98d4ff)

I suggest we add AkordJS as an additional project in the Dev tooling. Will you please submit the project?
Thanks a lot :)

**Comment by pascaljb** [comment]
Thanks @nicolasverlhiac ! I have just submitted a new project for AkordJS.
