### ISSUE TITLE
📨 [NEW]: AkordJS

### ISSUE THREAD

**Issue by pascaljb** [nicolasverlhiac/arweave-list#16]
### What is the project’s name ?

AkordJS

### Please provide a short description of this project.

AkordJS provides developers with the Akord Vault toolkit - a system for creating digital vaults on Arweave that have the following management features:
- File organization
- File versioning
- Access control
- End-to-end encryption with key rotation for collaboration
- Path manifests
- Private messaging
- Note creation
- UDL licensing
- Minting of Atomic NFTs, single and collections
- Importing of existing Arweave files

### This project is a decentralized alternative to which service/app?

AWS, Google, Azure

### In which category does this project fit (one or more)?

Developer Tooling

### Project logo

![Akord Twitter icon](https://github.com/nicolasverlhiac/arweave-list/assets/57722629/7ec7eaa8-5597-4693-89c6-d33469b3b78c)

### Link to the projet

https://github.com/Akord-com/akord-js

### Twitter @name

@AkordTeam

### Discord invitation link

https://discord.com/invite/DVkyUtcKGn

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @pascaljb , thank you for your help ! 
![CleanShot 2024-03-29 at 09 11 36@2x](https://github.com/nicolasverlhiac/arweave-list/assets/5034521/f6cb9552-c545-4653-8c55-6bdfa331b321)

**Comment by pascaljb** [comment]
Cool! thanks @nicolasverlhiac
