### ISSUE TITLE
📨 [NEW]: Add BetterIDEa IDE to the list

### ISSUE THREAD

**Issue by ankushKun** [nicolasverlhiac/arweave-list#17]
### What is the project’s name ?

BetterIDEa

### Please provide a short description of this project.

A suite of developer tools that make it super easy to start building on AO.
Including a feature rich web IDE, Package manager for AO, Portable AO code cells

### This project is a decentralized alternative to which service/app?

NA

### In which category does this project fit (one or more)?

Developer Tooling

### What are the tags that best describe this project?

free, open-source, smart-contract, dapp

### Project logo

![image](https://github.com/user-attachments/assets/2e260567-6772-465a-a2ce-e32908f93259)

### Link to the projet

https://betteridea.dev

### Permaweb link to the projet

https://betteridea.arweave.net

### Twitter @name

@betteridea_dev

### Discord invitation link

https://discord.gg/nm6VKUQBrA

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @ankushKun, thank you for your contribution ! (I love your project) 

BetterIDEa has been added to the list !
https://list.weavescan.com/project/betterIDEa

![screenshot_20240911_vuWoqozp_134507@2x](https://github.com/user-attachments/assets/e3677b62-cb46-41fc-8d3a-d5580c9147c1)
