### ISSUE TITLE
📨 [NEW]: Helix

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#19]
### What is the project’s name ?

Helix

### Please provide a short description of this project.

Helix is an atomic asset uploader. Digital content uploaded through Helix can be traded on the permaweb. 

### This project is a decentralized alternative to which service/app?

N/A

### In which category does this project fit (one or more)?

NFT, Publishing

### What are the tags that best describe this project?

beta, open-source, nft

### Project logo

![helix-logo (1)](https://github.com/user-attachments/assets/144bb7a3-28d1-499b-aa89-bd2683c00953)

### Link to the projet

https://helix.arweave.net/

### Discord invitation link

https://discord.gg/weavers

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
hi @afisher3578 ,

Thank you for your contribution. I have a question to make sure I don't miss anything. Is there a repository accessible with the open-source tag?

**Comment by afisher3578** [comment]
Hi @nicolasverlhiac here is the repo: https://github.com/permaweb/helix

**Comment by nicolasverlhiac** [comment]
Thank you ! The project has been added : https://list.weavescan.com/project/helix
