### ISSUE TITLE
📨 [NEW]: Permaverse

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#20]
### What is the project’s name ?

Permaverse

### Please provide a short description of this project.

The first full web3 metaverse, gaming hub and launchpad.

### This project is a decentralized alternative to which service/app?

N/A

### In which category does this project fit (one or more)?

Social

### What are the tags that best describe this project?

free, beta, game

### Project logo

![logoSOLO](https://github.com/user-attachments/assets/1abd1feb-d4ea-4e1e-beaf-c4cbab4f7f9b)

### Link to the projet

https://dumdum.arweave.net/

### Twitter @name

https://x.com/ThePermaverse

### Discord invitation link

https://discord.com/invite/QCk5qfvB3x

### Are you related to this project?

- [ ] I am related to this project

**Comment by afisher3578** [comment]
@nicolasverlhiac is it possible to include a new category called "gaming"? I don't think social represents what the app is fully. I have a list of other games I would like to add to Arweavelist as well.

**Comment by nicolasverlhiac** [comment]
Hi @afisher3578, I completely agree with you. I've added the `Gaming` category to Arweavelist, thank you ! 
It's an excellent idea and it will help better represent gaming projects!
