### ISSUE TITLE
📨 [NEW]: Llama Land

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#21]
### What is the project’s name ?

Llama Land

### Please provide a short description of this project.

AI powered MMO game built on AO and Arweave. 

### This project is a decentralized alternative to which service/app?

N/A

### In which category does this project fit (one or more)?

Social

### What are the tags that best describe this project?

free, beta, open-source, game

### Project logo

![llama](https://github.com/user-attachments/assets/3e3f3184-701a-4d48-8b35-4acbd0d0f0e9)

### Link to the projet

https://llamaland.arweave.net/

### Twitter @name

https://x.com/LlamaLandAO

### Discord invitation link

https://discord.gg/dYXtHwc9dc

### Are you related to this project?

- [ ] I am related to this project

**Comment by afisher3578** [comment]
Open source repo - https://github.com/elliotsayes/Reality

**Comment by nicolasverlhiac** [comment]
Hi @afisher3578, Thank you for your contributions, it's really great!
