### ISSUE TITLE
📨 [NEW]: ArFleet

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#23]
### What is the project’s name ?

ArFleet

### Please provide a short description of this project.

ArFleet enables temporary storage on Arweave to lower prices for apps to scale for their users.

### This project is a decentralized alternative to which service/app?

NA

### In which category does this project fit (one or more)?

Developer Tooling, Infrastructure, Storage

### What are the tags that best describe this project?

beta, database

### Project logo

![Arfleet](https://github.com/user-attachments/assets/b90aeafd-2e88-4613-adaa-df1ba1e5824c)

### Link to the projet

https://arfleet.io/

### Twitter @name

https://x.com/aoaccorg

### Discord invitation link

https://discord.com/invite/CetKmVxwG4

### Are you related to this project?

- [ ] I am related to this project

**Comment by afisher3578** [comment]
https://github.com/aoacc

**Comment by nicolasverlhiac** [comment]
Thank you @afisher3578, this project has been added : https://list.weavescan.com/project/ArFleet
