### ISSUE TITLE
📨 [NEW]: Autonomous Finance

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#24]
### What is the project’s name ?

Autonomous Finance

### Please provide a short description of this project.

Autonomous Finance is a dedicated research and technology entity, focusing on the intricacies of financial infrastructure within the ao network.

### This project is a decentralized alternative to which service/app?

NA

### In which category does this project fit (one or more)?

Developer Tooling, Infrastructure, Analytics

### What are the tags that best describe this project?

open-source, smart-contract, dapp

### Project logo

![autonomous-finance](https://github.com/user-attachments/assets/24c26f7b-f74c-4093-9ea4-190539dfdf45)

### Link to the projet

https://www.autonomous.finance/

### Twitter @name

https://x.com/autonomous_af

### Discord invitation link

https://discord.gg/AK6C2PPWDc

### Are you related to this project?

- [ ] I am related to this project

**Comment by afisher3578** [comment]
https://github.com/Autonomous-Finance

**Comment by nicolasverlhiac** [comment]
Thank you @afisher3578, this project has been added : https://list.weavescan.com/project/autonomous-finance
