### ISSUE TITLE
📨 [NEW]: AOX

### ISSUE THREAD

**Issue by afisher3578** [nicolasverlhiac/arweave-list#25]
### What is the project’s name ?

AOX

### Please provide a short description of this project.

Bridge assets to the AO ecosystem with AOX. Built by EverVision Labs.

### This project is a decentralized alternative to which service/app?

NA

### In which category does this project fit (one or more)?

Exchange

### What are the tags that best describe this project?

beta

### Project logo

![aox](https://github.com/user-attachments/assets/2aa8a369-dcbe-4f7c-82e0-c85cf3c68489)

### Link to the projet

https://aox.arweave.net/#/

### Twitter @name

https://x.com/aox_xyz

### Discord invitation link

https://discord.gg/ERXDrzyqF8

### Are you related to this project?

- [ ] I am related to this project

**Comment by nicolasverlhiac** [comment]
Thank you @afisher3578, this project has been added : https://list.weavescan.com/project/AOX
