### ISSUE TITLE
📨 [NEW]: ArConnect

### ISSUE THREAD

**Issue by martonlederer** [nicolasverlhiac/arweave-list#3]
### What is the project’s name ?

ArConnect

### Please provide a short description of this project.

Secure wallet management for Arweave. ArConnect provides simple and effective way to interact with Permaweb Apps.

### This project is a decentralized alternative to which service/app?

-

### In which category does this project fit (one or more)?

Wallet

### What are the tags that best describe this project?

non-custodial-wallet, cross-browser, free, open-source, cross-plateform

### Project logo

![icon512](https://user-images.githubusercontent.com/30638105/214783733-211638e2-4f99-4378-a178-8532478615b4.png)

### Link to the projet

https://arconnect.io

### Twitter @name

@arconnectio

### Discord invitation link

https://discord.gg/gzHeuZS3Rb

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @martonlederer , it's a real pleasure to meet you here, thank you very much for your contribution! The list of Wallets is growing :
<img width="818" alt="Capture d’écran 2023-01-27 à 13 45 06" src="https://user-images.githubusercontent.com/5034521/215090238-b7ad597a-3311-4cdf-bcef-b3db15905f6e.png">

**Comment by martonlederer** [comment]
Very cool, thank you! Nice to e-meet you too :D
