### ISSUE TITLE
📨 [NEW]: ECHO

### ISSUE THREAD

**Issue by airyland** [nicolasverlhiac/arweave-list#4]
### What is the project’s name ?

ECHO

### Please provide a short description of this project.

ECHO is the first decentralized social engagement protocol based on Arweave to help collecting comments, reactions and receiving tips.

### This project is a decentralized alternative to which service/app?

Disqus

### In which category does this project fit (one or more)?

Social, Publishing, Infrastructure, Storage

### What are the tags that best describe this project?

cross-browser, web-app, open-source, protocol, social-network

### Project logo

![android-chrome-512x512](https://user-images.githubusercontent.com/559179/214892729-38140e9e-3ea2-4ecd-baae-3077a3c69c5b.png)

### Link to the projet

https://0xecho.com

### Twitter @name

@0x_ECHO

### Discord invitation link

https://discord.com/invite/KFxyaw9Wdj

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @airyland , thank you very much for your contribution. ECHO is a great project, you have done an incredible job !

<img width="817" alt="Capture d’écran 2023-01-27 à 13 46 15" src="https://user-images.githubusercontent.com/5034521/215090434-812c87c5-7b2a-458b-9179-f42548279ceb.png">
