### ISSUE TITLE
📨 [NEW]:

### ISSUE THREAD

**Issue by arweavebull** [nicolasverlhiac/arweave-list#5]
### What is the project’s name ?

FirstBatch

### Please provide a short description of this project.

FirstBatch is on a mission to make personalization self-sovereign, interoperable and privacy-preserving. FirstBatch is building the Universal Interest Graph to offer decentralized personalization with interoperable data while preserving user privacy. 

### This project is a decentralized alternative to which service/app?

Centralized Similarity Search Engines: Milvus

Centralized Interest Graphs of web2.0 tech giants: Tiktok, Facebook, etc

### In which category does this project fit (one or more)?

Infrastructure

### What are the tags that best describe this project?

open-source, protocol, social-network

### Project logo

![905739D3-FEDB-4BC8-9818-733B88EA7A04](https://user-images.githubusercontent.com/123092740/215077045-c167c951-6fb5-4c3b-a447-c1aaa5ad4b9d.jpeg)

### Link to the projet

www.firstbatch.xyz

### Twitter @name

@FirstBatchxyz_

### Are you related to this project?

- [ ] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @arweavebull, thank you very much for your contribution, the list is growing with FirstBatch!

<img width="812" alt="Capture d’écran 2023-01-27 à 13 52 28" src="https://user-images.githubusercontent.com/5034521/215091543-ebc4ba26-a031-4748-8ed8-ae995ed5311c.png">
