### ISSUE TITLE
📨 [NEW]: Glacier Network

### ISSUE THREAD

**Issue by GlacierNetwork** [nicolasverlhiac/arweave-list#6]
### What is the project’s name ?

Glacier Network

### Please provide a short description of this project.

Glacier is building a fully permissionless, dynamic and scalable NoSQL database for Web3 Dapps. Glacier empowers decentralized apps to build on decentralized databases. It provides programmable data composability solutions to easily and effortlessly handle data within the core of the Glacier with scalability, resilience, data security and privacy.

### This project is a decentralized alternative to which service/app?

MongoDB

### In which category does this project fit (one or more)?

Infrastructure

### What are the tags that best describe this project?

database

### Project logo

![Glacier](https://user-images.githubusercontent.com/119845846/219267870-350066aa-3784-4292-b661-898ca5449a81.jpeg)

### Link to the projet

https://www.glacier.io/

### Twitter @name

https://twitter.com/Glacier_Labs

### Discord invitation link

https://discord.gg/eYAGGz5W3b

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @GlacierNetwork ,
Thank you for your help, the list has been updated with **Glacier Network** !

<img width="798" alt="Capture d’écran 2023-02-16 à 10 29 58" src="https://user-images.githubusercontent.com/5034521/219324819-6fbbaca3-4bff-4182-8b6c-5650b288013e.png">

**Comment by GlacierNetwork** [comment]
> Hi @GlacierNetwork , Thank you for your help, the list has been updated with **Glacier Network** !
> 
> <img alt="Capture d’écran 2023-02-16 à 10 29 58" width="798" src="https://user-images.githubusercontent.com/5034521/219324819-6fbbaca3-4bff-4182-8b6c-5650b288013e.png">
 
Hi Nicolas, may I bother you to move us from "Infrastructure"  to "Developer tooling" category please? Sorry for the inconvenience caused.

**Comment by GlacierNetwork** [comment]
> Hi @GlacierNetwork , Thank you for your help, the list has been updated with **Glacier Network** !
> 
> <img alt="Capture d’écran 2023-02-16 à 10 29 58" width="798" src="https://user-images.githubusercontent.com/5034521/219324819-6fbbaca3-4bff-4182-8b6c-5650b288013e.png">

Hey Nicolas, may I bother you to move us from "Infrastructure" to "Developer Tooling" category? Sorry for the inconvenience caused.

**Comment by nicolasverlhiac** [comment]
No problem, it's already done 🙂
