### ISSUE TITLE
📨 [NEW]: Storedat.io

### ISSUE THREAD

**Issue by narbs91** [nicolasverlhiac/arweave-list#7]
### What is the project’s name ?

Storedat.io

### Please provide a short description of this project.

Storedat is a GraphQL API built on top of Web3 storage providers like Arweave and Filecoin. We exist to accelerate the adoption of decentralized storage by providing a provider agnostic way to read and write data with those protocols all the while abstracting web3 away from the user. No dealing with wallets, signing transactions, managing private keys, paying transaction costs, and so on. Just plug in and Storedat

### This project is a decentralized alternative to which service/app?

Storedat is an abstraction layer over foundational decentralized storage providers like Arweave and Filecoin meant to improve the developer experience.  While we might start with Filecoin and Arweave today, our vision is to expand out and support more storage providers in the future.  The ultimate goal is to have Storedat become the goto hub for anyone to plug and play with decentralized storage.

### In which category does this project fit (one or more)?

Developer Tooling, Infrastructure, Storage

### What are the tags that best describe this project?

beta, cross-plateform, database

### Project logo

![storedat icon](https://user-images.githubusercontent.com/29411347/219562387-6f4bd5ed-47d1-4f0b-a3a6-a74f9481e089.png)

### Link to the projet

https://storedat.io

### Twitter @name

@storedat_io

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @narbs91 !
Thanks for your help and contribution, the list has been updated:

<img width="801" alt="Capture d’écran 2023-02-17 à 11 20 13" src="https://user-images.githubusercontent.com/5034521/219617645-2fefe8db-c045-46e7-b72b-0b9280933c88.png">
