### ISSUE TITLE
📨 [NEW]: Arweave.name

### ISSUE THREAD

**Issue by angrymouse** [nicolasverlhiac/arweave-list#9]
### What is the project’s name ?

Arweave.Name

### Please provide a short description of this project.

Arweave.Name is arweave-powered nameserver service.

### This project is a decentralized alternative to which service/app?

PowerDNS, Cloudflare, Namecheap

### In which category does this project fit (one or more)?

Infrastructure

### What are the tags that best describe this project?

free, open-source, dapp

### Project logo

![logo-01](https://user-images.githubusercontent.com/40735471/219817871-2eaf5215-2382-4715-ba23-7a845e1f13aa.png)

### Link to the projet

https://arweave.name

### Are you related to this project?

- [X] I am related to this project

**Comment by nicolasverlhiac** [comment]
Hi @angrymouse, 

Thank you again, your contribution improves the list :)

<img width="790" alt="Capture d’écran 2023-02-23 à 20 04 26" src="https://user-images.githubusercontent.com/5034521/221005410-583bba05-ef07-4e4b-8a8a-6ce9a1c13904.png">
